### ISSUE TITLE
ox-ipynb: No new paragraph after blank lines and all subsections are H1

### ISSUE THREAD

**Issue by singletS** [jkitchin/scimax#68]
I recently cloned scimax on a machine running emacs 25.2.  Using the following org input, I'm noticing two issues:
- Cannot start new paragraphs using blank lines if text is after section heading (text before the first section works fine).
- All the subsection titles are exported with a single # in markdown cells (probably not helpful due to age, but as of commit ac2479d subsections kept all their #'s)

Org snippet:
```
Text before a section behaves as expected.

Giving a new paragraph after an empty line.

* New section
After a section, however, blank lines seem to get stripped.

New paragraph should be begin here.


But it doesn't.

** Workarounds

New paragraphs can be forced
<p>

With an html ~<p>~ or
\\
a double backslash at beginning of line.


A line by itself.

After an empty line.

*** Subsubsection
Markdown conversion is losing depth in sections. 

All sections are first level headings in ipynb markdown cells.
```

**Comment by jkitchin** [comment]
hm. It seems like something has changed, the sublevels definitely used to work. The markdown export is dropping all the levels. I will try to look into it tomorrow.

**Comment by jkitchin** [comment]
I just pushed two fixes for these issues. I don't know why cl-flet stopped working here. For now I am going back to flet, which does work although now you will see this: ‘flet’ is an obsolete macro (as of 24.3); use either ‘cl-flet’ or ‘cl-letf’.

**Comment by singletS** [comment]
Further messing around shows weird (to me anyway) behavior I'll add here for reference:
- Pulled from github master into an existing scimax repo, byte-force-recompile, and cleared my additions to user.el: the sublevels issue is fixed, but the new paragraph/newline issue remains. Tried wiping elpa directory and re-installing packages with same results.
- Re-cloning a "pristine" copy from github: both issues are fixed!?

Regardless of what's going on in the existing repo, I've got ox-ipynb working, and have not (yet) noticed any warning or message about the obsolete flet macro with emacs 25.2.2, linux.

Feel free to close the issue unless it's worth digging further on this.
Thanks

**Comment by jkitchin** [comment]
weird. I pushed another change to use cl-letf which removed the obsolete macro warning. That is probably why you didn't see it.

I am not totally sure the new paragraph/newline issue is totally fixed. Do you think paragraphs should get their own markdown cells?

**Comment by singletS** [comment]
I'll follow up if newline issues reappear.

RE paragraph-level md cells: Interesting idea, but probably no. I noticed this issue trying to separate about 10 sentence fragments with whitespace to give visual markup but kept the logical unit together.  In this case, ~10 separate cells would be cumbersome to edit for jupyter notebook users, and break apart the unit of prose. I do like having control over md cell breaks with #+ipynb-newcell, though.

(OTOH, someday I'd like to play with nbdime for versioning/comparing student notebooks.  I don't know if 1 paragraph = 1 markdown cell would help or hinder this...?)

**Comment by jkitchin** [comment]
You will probably want to set ox-ipynb-paragraph-separate-cells to nil the next time you update then ;) In many of my lectures I would end up with 3-4 paragraphs in one cell which I also found annoying to edit in class. I am not sure the recent addition will stay, but it could be turned off by setting it to nil.

Interesting idea with nbdime, I don't know how it would differ.

**Comment by singletS** [comment]
Yep, I've found relief with the annoyingly-long-cell-in-class problem using #ipynb-newcell.  I'll give the approach a try.

Where is `ox-ipynb-filter-paragraph` defined?  I'm getting
```org-export-filter-apply-functions: Symbol’s function definition is void: ox-ipynb-filter-paragraph```.

**Comment by jkitchin** [comment]
I took that function out and forgot to remove that line. I am out of the office now, and can't push the fix, but I will do it later tonight or tomorrow.

**Comment by singletS** [comment]
No rush...I got it working.
